apiVersion: apps/v1
kind: Deployment
metadata:
  name: respeer-docs-webui
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: respeer-docs-webui
  template:
    metadata:
      labels:
        app: respeer-docs-webui
    spec:
      containers:
        - name: respeer-docs-webui
          image: DOCKER_REGISTRY/linera/respeer-docs-webui:latest
          imagePullPolicy: Always
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: respeer-docs-webui
  namespace: kube-system
spec:
  ports:
    - name: api
      port: 3000
      targetPort: 3000
  selector:
    app: respeer-docs-webui
